import "./globals.css";

import React from "react";
import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";

import { cn } from "@acervo/lib/utils";
import { Toaster } from "@acervo/components/ui/sonner";
import { ReactQueryClientProvider } from "@acervo/contexts/react-query";
import { Header } from "@acervo/components/header";
import Footer from "@acervo/components/footer";

const mulish = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Acervo",
  description: "Generated by Acervo",
  icons: {
    icon: "/images/logo.svg",
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn("min-h-screen font-sans antialiased", mulish.className)}
      >
        <ReactQueryClientProvider>
          <div className="relative flex min-h-screen flex-col">
            <Header />
            <div className="flex-1">{children}</div>
            <Footer />
          </div>
        </ReactQueryClientProvider>
        <Toaster />
      </body>
    </html>
  );
}
