import "./globals.css";

import React from "react";
import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";

import { cn } from "@acervo/lib/utils";
import { ReactQueryClientProvider } from "@acervo/contexts/react-query";

const mulish = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Acervo",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn("min-h-screen font-sans antialiased", mulish.className)}
      >
        <ReactQueryClientProvider>
          <div className="relative flex min-h-screen flex-col">
            <div className="flex-1">{children}</div>
          </div>
        </ReactQueryClientProvider>
      </body>
    </html>
  );
}
